spring.application.name=multistorage-sample

spring.datasource.url=jdbc:postgresql://localhost:5432/multistorage
spring.datasource.username=multistorage
spring.datasource.password=multistorage
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

logging.level.liquibase=INFO
logging.level.liquibase.executor=INFO
logging.level.org.springframework.boot.autoconfigure.liquibase=INFO
logging.level.org.springframework.boot=INFO

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

